import { Metadata } from "next";

import { getRealDomain } from "@/utils/domainUtils";

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next shop",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Get real domain from proxy headers
  const domain = getRealDomain();
  return (
    <>
      <div className="">{children}</div>
    </>
  );
}
