import Header from "./components/Header";
import Layout from "./components/Layout";
import "./css/globals.css";
import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/Footer";
import BottomNavigation from "./components/BottomNavigation";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";

export const metadata: Metadata = {
  title: "My Smart Shop ",
  description: "Generated by create next shop",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sessionServer = await getServerSession(options);
  // const token = sessionServer?.bearer;
  // const res = await fetch("http://127.0.0.1:8000/api/user/profile", {
  //   headers: {
  //     "Content-Type": "application/json",
  //     Authorization: `Bearer ${token}`,
  //   },
  // });
  // const data = await res.json();
  // console.log(process.env.GITHUB_ID!);
  return (
    <html lang="en">
      <body className="font-bodyFont w-full bg-main-bg text-darkText ">
        <Layout>
          <Header />
          {children}
          <BottomNavigation />
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
