import Header from "./components/Header";
import Layout from "./components/Layout";
import "./css/globals.css";
import type { Metadata } from "next";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/Footer";
import BottomNavigation from "./components/BottomNavigation";

export const metadata: Metadata = {
  title: "My Smart Shop ",
  description: "Generated by create next shop",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-bodyFont w-full bg-main-bg text-darkText ">
        <Layout>
          <Header />
          {children}
          <BottomNavigation />
          <Footer />
        </Layout>
      </body>
    </html>
  );
}
