import './css/globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import { getServerSession } from 'next-auth';
import { headers } from 'next/headers';

import { options } from './api/auth/[...nextauth]/options';
import LayoutWeb from './components/landingpage/Layout';
import Layout from './components/Layout';
import LayoutCustom from './components/LayoutCustom';
import { ShopDataProvider } from './components/shop/ShopContext';
import { LayoutProvider } from './LayoutProvider';

// export const metadata: Metadata = {
//   title: "Smart Shop ",
//   description: "Generated by create next shop",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const sessionServer = await getServerSession(options);
  // const token = sessionServer?.bearer;
  // const res = await fetch("http://127.0.0.1:8000/api/user/profile", {
  //   headers: {
  //     "Content-Type": "application/json",
  //     Authorization: `Bearer ${token}`,
  //   },
  // });
  // const data = await res.json();
  // console.log(process.env.GITHUB_ID!);

  /** */
  const headersList = headers();
  const domain = headersList.get("host") || "";
  const fullUrl = headersList.get("referer") || "";
  const [, pathname] =
    fullUrl.match(new RegExp(`https?:\/\/${domain}(.*)`)) || [];
  // console.log(pathname);
  // console.log(domain);

  /**
   <Provider store={store}>
      <PersistGate persistor={persistor}>
        <SessionProvider>
          <UserDataProvider>{children}</UserDataProvider>
        </SessionProvider>
      </PersistGate>
    </Provider>
    
   */
  if (process.env.LANDING_PAGE?.includes(domain)) {
    return (
      <html lang="en">
        <meta charSet="UTF-8" />
        <head>
          <title>My Shop Page</title>
          {domain === "tokokiens.com" ? (
            <link rel="icon" href="/images/favicon.png" />
          ) : domain === "bangkokmiracle.store" ? (
            <link
              rel="icon"
              href={`${process.env.SERVER_ENDPOINT}/images/favicon_bangkokmiracle.jpg`}
            />
          ) : (
            <link
              rel="icon"
              href={`${process.env.SERVER_ENDPOINT}/images/favicon.jpg`}
            />
          )}
        </head>
        <body className="font-bodyFont w-full bg-main-bg text-darkText ">
          <LayoutProvider>
            <ShopDataProvider domain={domain}>
              <LayoutWeb>{children}</LayoutWeb>
            </ShopDataProvider>
          </LayoutProvider>
        </body>
      </html>
    );
  } else {
    const sessionServer = await getServerSession(options);
    const token = sessionServer?.bearer;
    
    // Default values in case of fetch failure
    let data = {
      domain: domain,
      description: "",
      logo: "",
      company_name: "My Shop",
      favicon: "",
    };

    try {
      // Create AbortController for timeout
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout

      const res = await fetch(
        `${process.env.SERVER_ENDPOINT}/api/shop/${domain}`,
        {
          signal: controller.signal,
          headers: {
            "Accept": "application/json",
            "User-Agent": "Next.js",
          },
          // Add cache options to help with reliability
          cache: "no-store", // Always fetch fresh data
        }
      );

      clearTimeout(timeoutId);

      if (res.ok) {
        data = await res.json();
      } else {
        console.error(`Failed to fetch shop data: ${res.status} ${res.statusText}`);
      }
    } catch (error: any) {
      // Handle abort (timeout)
      if (error.name === "AbortError") {
        console.error("Request timeout: Failed to fetch shop data within 10 seconds");
      } else {
        console.error("Error fetching shop data:", error.message);
        
        // If it's an SSL error, provide helpful error message
        if (
          error.code === "ERR_SSL_SSLV3_ALERT_HANDSHAKE_FAILURE" ||
          error.code === "ERR_TLS_CERT_ALTNAME_INVALID" ||
          error.code === "CERT_HAS_EXPIRED" ||
          error.message?.includes("SSL") ||
          error.message?.includes("handshake") ||
          error.message?.includes("certificate")
        ) {
          console.error(
            "\n⚠️  SSL/TLS Certificate Error Detected!\n" +
            "Possible solutions:\n" +
            "1. For development with self-signed certificates, set NODE_TLS_REJECT_UNAUTHORIZED=0 (NOT for production)\n" +
            "2. Ensure SERVER_ENDPOINT uses a valid SSL certificate\n" +
            "3. Verify the certificate hasn't expired\n" +
            "4. Check if SERVER_ENDPOINT should use HTTP instead of HTTPS for development\n" +
            `Current SERVER_ENDPOINT: ${process.env.SERVER_ENDPOINT}\n`
          );
        }
      }
      // Continue with default values so the page still renders
    }

    const {
      domain: domainName,
      description,
      logo,
      company_name,
      favicon,
    } = data;

    return (
      <html lang="en">
        <head>
          <title>{company_name}</title>
          {favicon && (
            <link
              rel="icon"
              href={`${process.env.SERVER_ENDPOINT}/storage/logo/${favicon}`}
            />
          )}
        </head>
        <body className="font-bodyFont w-full bg-main-bg text-darkText ">
          <LayoutProvider>
            <ShopDataProvider domain={domain}>
              <Layout>
                <LayoutCustom>{children}</LayoutCustom>
              </Layout>
            </ShopDataProvider>
          </LayoutProvider>
        </body>
      </html>
    );
  }
}
